package icons

const (
	APPLICATION = "ﬓ"
	AWS         = ""
	BUCKET      = ""
	BUG         = ""
	CHART       = ""
	DATABASE    = ""
	FILE        = ""
	FILE_CODE   = ""
	FILES       = ""
	FOLDER      = ""
	INFO        = ""
	KEY         = ""
	LIST        = ""
	LOCATION    = ""
	PLAY        = ""
	SCHEMA      = "ﴳ"
	SHIELD      = ""
	TABLE       = ""
	TAG         = ""
	TASKS       = ""
	USER        = ""
	USER_CIRCLE = ""
	LAMBDA      = "ﬦ"
	ARROW_UP    = "▲"
	ARROW_DOWN  = "▼"
)
